***************
*** 1,6 ****
  prefix=/usr
- includedir=$(prefix)/include
- libdir=$(prefix)/lib
  
  ARCH := $(shell uname -m | sed -e s/i.86/i386/)
  CFLAGS := -nostdlib -nostartfiles -Wall -I. -g -fomit-frame-pointer -O2 -fPIC
--- 1,7 ----
  prefix=/usr
+ includedir=/usr/include
+ libdir=/usr/lib
+ usrlibdir=/usr/lib
  
  ARCH := $(shell uname -m | sed -e s/i.86/i386/)
  CFLAGS := -nostdlib -nostartfiles -Wall -I. -g -fomit-frame-pointer -O2 -fPIC
***************
*** 51,61 ****
  	$(CC) $(SO_CFLAGS) -Wl,--version-script=libaio.map -Wl,-soname=$(soname) -o $@ $(libaio_sobjs) $(LINK_FLAGS)
  
  install: $(all_targets)
- 	install -D -m 644 libaio.h $(includedir)/libaio.h
- 	install -D -m 644 libaio.a $(libdir)/libaio.a
- 	install -D -m 755 $(libname) $(libdir)/$(libname)
- 	ln -sf $(libname) $(libdir)/$(soname)
- 	ln -sf $(libname) $(libdir)/libaio.so
  
  $(libaio_objs): libaio.h
  
--- 52,62 ----
  	$(CC) $(SO_CFLAGS) -Wl,--version-script=libaio.map -Wl,-soname=$(soname) -o $@ $(libaio_sobjs) $(LINK_FLAGS)
  
  install: $(all_targets)
+ 	install -D -m 644 libaio.h $(destdir)$(includedir)/libaio.h
+ 	install -D -m 644 libaio.a $(destdir)$(usrlibdir)/libaio.a
+ 	install -D -m 755 $(libname) $(destdir)$(libdir)/$(libname)
+ 	ln -sf $(libdir)/$(libname) $(destdir)$(libdir)/$(soname)
+ 	ln -sf $(libdir)/$(libname) $(destdir)$(usrlibdir)/libaio.so
  
  $(libaio_objs): libaio.h
  
